configMap:
  name: govstack-xroad-ssc-config
  labels:
    app: govstack-xroad-ssc-config
postgresStorage:
  volName: govstack-xroad-ssc-postgres-pv-volume
  claimName: govstack-xroad-ssc-postgres-pv-claim
  labels:
    type: local
    app: postgres
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/mnt/data"
postgresDeployment:
  name: govstack-xroad-ssc-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: govstack-xroad-ssc-postgres
            image: postgres:12
            imagePullPolicy: "IfNotPresent"
            containerPort: 5432
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb
            volumeName: postgredb
            volumeClaimName: govstack-xroad-ssc-postgres-pv-claim
            env:
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssc-postgres-admin-db-info-secret
                    key: dbname 
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssc-postgres-admin-db-info-secret
                    key: username             
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssc-postgres-admin-secret
                    key: password             
        volumes:
          - name: postgredb
            claimName: govstack-xroad-cs-postgres-pv-claim
postgresService:
  name: govstack-xroad-ssc-postgres
  labels:
    app: postgres
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres
secret:
  postgres:
    adminDbInfo:
      name: govstack-xroad-ssc-postgres-admin-db-info-secret
      type: Opaque  
    adminPassword:
      name: govstack-xroad-ssc-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssc-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssc-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssc-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssc-postgres-messagelog-secret
      type: Opaque                  
service:
  name: govstack-xroad-ssc
  type: ClusterIP
deployment:
  name: govstack-xroad-ssc
  containers:
    name: govstack-xroad-ssc
    imageName: xroad-ssc
    imagePullPolicy: "Always"
    configMapName: govstack-xroad-ssc-config
    #env:
    #  - name: "DB_HOST"
    #    value: "${SSC_DB_HOST}"
    #  - name: "DB_PORT"
    #    value: "${SSC_DB_PORT}"
    #  - name: "DB_ADMIN_USER"
    #    value: "${SSC_DB_ADMIN_USER}"
    #  - name: "DB_ADMIN_PASS"
    #    value: "${SSC_DB_ADMIN_PASS}"        
    #  - name: "DB_SERVERCONF_ADMIN_PASS"
    #    value: "${SSC_DB_SERVERCONF_ADMIN_PASS}"
    #  - name: "DB_SERVERCONF_PASS"
    #    value: "${SSC_DB_SERVERCONF_PASS}"
    #  - name: "DB_NESSAGELOG_ADMIN_PASS"
    #    value: "${SSC_DB_NESSAGELOG_ADMIN_PASS}"
    #  - name: "DB_MESSAGELOG_PASS"
    #    value: "${SSC_DB_MESSAGELOG_PASS}"                                                                    

