configMap:
  name: govstack-xroad-ssc-config
  labels:
    app: govstack-xroad-ssc-config
postgresStorage:
  volName: govstack-xroad-ssc-postgres-pv-volume
  claimName: govstack-xroad-ssc-postgres-pv-claim
  labels:
    type: local
    app: postgredb-ssc
  spec:
    storageClassName: manual
    persistentVolumeReclaimPolicy: Delete
    capacity:
      storage: 5Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/data/postgresql"
postgresDeployment:
  name: govstack-xroad-ssc-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres-ssc
    template:
      metadata:
        labels:
          app: postgres-ssc
      spec:
        containers:
          - name: govstack-xroad-ssc-postgres
            image: postgres:12
            imagePullPolicy: "Always"
            containerPort: 5432
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb-ssc
            volumeName: postgredb-ssc
            volumeClaimName: govstack-xroad-ssc-postgres-pv-claim
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssc-postgres-admin-secret
                    key: password             
        volumes:
          - name: postgredb-ssc
            claimName: govstack-xroad-ssc-postgres-pv-claim
postgresService:
  name: govstack-xroad-ssc-postgres
  labels:
    app: postgres-ssc
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres-ssc
secret:
  postgres:
    adminDbInfo:
      name: govstack-xroad-ssc-postgres-admin-db-info-secret
      type: Opaque  
    adminPassword:
      name: govstack-xroad-ssc-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssc-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssc-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssc-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssc-postgres-messagelog-secret
      type: Opaque                  
service:
  name: govstack-xroad-ssc
  type: ClusterIP
deployment:
  name: govstack-xroad-ssc
  containers:
    name: govstack-xroad-ssc
    imageName: xroad-ssc
    imagePullPolicy: "Always"
    configMapName: govstack-xroad-ssc-config
