postgres:
  storage:
    volName: govstack-xroad-cs-postgres-pv-volume
    claimName: govstack-xroad-cs-postgres-pv-claim
    labels:
      type: local
      app: postgres-cs
    spec:
      storageClassName: manual
      persistentVolumeReclaimPolicy: Delete
      capacity:
        storage: 5Gi
      accessMode: ReadWriteOnce
      hostPath:
        path: "/mnt/data"
  deployment:
    name: govstack-xroad-cs-postgres
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgres-cs
      temp:
        metadata:
          labels:
            app: postgres-cs
        spec:
          containers:
              name: govstack-xroad-cs-postgres
              image: postgres:12
              imagePullPolicy: "Always"
              containerPort: 5432
              volumeMountName: postgredb-cs
              volumeName: postgredb-cs
              passwordSecretName: govstack-xroad-cs-postgres-admin-secret
              volumeClaimName: govstack-xroad-cs-postgres-pv-claim
          volumes:
            - name: postgredb-cs
              claimName: govstack-xroad-cs-postgres-pv-claim
  service:
    name: govstack-xroad-cs-postgres
    labels:
      app: postgres-cs
    spec:
      type: NodePort
      port: 5432
      selector:
        app: postgres-cs
secret:
  postgres:
    adminPassword:
      name: govstack-xroad-cs-postgres-admin-secret
      type: Opaque
    uiPassword:
      name: govstack-xroad-cs-postgres-centerui-secret
      type: Opaque
application:
  service:
    name: govstack-xroad-cs
    type: ClusterIP
  deployment:
    name: govstack-xroad-cs
    containers:
      name: govstack-xroad-cs
      imageName: xroad-cs
      imagePullPolicy: "Always"

