kind: Namespace
metadata:
  name: govstack
---
kind: Service
metadata:
  name: govstack-xroad-cs
  labels:
    run: govstack-xroad-cs
  namespace: govstack
spec:
  type: ClusterIP
  selector:
    run: govstack-xroad-cs
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: ocsp
    - port: 8899
      targetPort: 8899
      protocol: TCP
      name: tsa
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: name1
    - port: 4002
      targetPort: 4002
      protocol: TCP
      name: name2      
---

kind: Deployment
metadata:
  name: govstack-xroad-cs
  namespace: govstack
spec:
  selector:
    matchLabels:
      run: govstack-xroad-cs
  replicas: 1
  template:
    metadata:
      labels:
        run: govstack-xroad-cs
    spec:
      containers:
        - name: govstack-xroad-cs
          image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/govstackecr:xroad-cs
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 4000
            - containerPort: 5500
            - containerPort: 5577
            - containerPort: 5588
             
