postgresConfigMap:
  name: govstack-xroad-cs-postgres-config
  labels:
    app: postgres
  data:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: ${XROAD_CS_POSTGRES_ADMIN_SECRET}
postgresStorage:
  volName: govstack-xroad-cs-postgres-pv-volume
  claimName: govstack-xroad-cs-postgres-pv-claim
  labels:
    type: local
    app: postgres
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/mnt/data"
postgresDeployment:
  name: govstack-xroad-cs-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: govstack-xroad-cs-postgres
            image: postgres:12
            imagePullPolicy: "IfNotPresent"
            containerPort: 5432
            configMapRef: govstack-xroad-cs-postgres-config
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb
            volumeName: postgredb
            volumeClaimName: govstack-xroad-cs-postgres-pv-claim
        volumes:
          - name: postgredb
            claimName: govstack-xroad-cs-postgres-pv-claim           
postgresService:
  name: govstack-xroad-cs-postgres
  labels:
    app: postgres
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres
secret:
  postgres:
    adminPassword:
      name: govstack-xroad-cs-postgres-admin-secret
      type: Opaque
    uiPassword:
      name: govstack-xroad-cs-postgres-centerui-secret
      type: Opaque
service:
  name: govstack-xroad-cs
  type: ClusterIP
deployment:
  name: govstack-xroad-cs
  containers:
    name: govstack-xroad-cs
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/${ECR_CS_REPO_NAME}:xroad-cs
    imagePullPolicy: "Always"
    env:
      - name: "DB_HOST"
        value: "${CS_DB_HOST}"
      - name: "DB_PORT"
        value: "${CS_DB_PORT}"
      - name: "DB_ADMIN_USER"
        value: "${CS_DB_ADMIN_USER}"
      - name: "DB_ADMIN_PASS"
        value: "${CS_DB_ADMIN_PASS}"                     
      - name: "DB_UI_PASS"
        value: "${CS_DB_UI_PASS}"

