configMap:
  name: govstack-xroad-cs-config
  labels:
    app: govstack-xroad-cs-config
postgresStorage:
  volName: govstack-xroad-cs-postgres-pv-volume
  claimName: govstack-xroad-cs-postgres-pv-claim
  labels:
    type: local
    app: postgredb-cs
  spec:
    storageClassName: manual
    persistentVolumeReclaimPolicy: Delete
    capacity:
      storage: 5Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/data/postgresql"
postgresDeployment:
  name: govstack-xroad-cs-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres-cs
    template:
      metadata:
        labels:
          app: postgres-cs
      spec:
        containers:
          - name: govstack-xroad-cs-postgres
            image: postgres:12
            imagePullPolicy: "Always"
            containerPort: 5432
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb-cs
            volumeName: postgredb-cs
            volumeClaimName: govstack-xroad-cs-postgres-pv-claim
            env:
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-cs-postgres-admin-db-info-secret
                    key: dbname
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-cs-postgres-admin-db-info-secret
                    key: username
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-cs-postgres-admin-secret
                    key: password
        volumes:
          - name: postgredb-cs
            claimName: govstack-xroad-cs-postgres-pv-claim           
postgresService:
  name: govstack-xroad-cs-postgres
  labels:
    app: postgres-cs
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres-cs
secret:
  postgres:
    adminDbInfo:
      name: govstack-xroad-cs-postgres-admin-db-info-secret
      type: Opaque
    adminPassword:
      name: govstack-xroad-cs-postgres-admin-secret
      type: Opaque
    uiPassword:
      name: govstack-xroad-cs-postgres-centerui-secret
      type: Opaque
service:
  name: govstack-xroad-cs
  type: ClusterIP
deployment:
  name: govstack-xroad-cs
  containers:
    name: govstack-xroad-cs
    imageName: xroad-cs
    imagePullPolicy: "Always"
    configMapName: govstack-xroad-cs-config

