postgresConfigMap:
  name: govstack-xroad-ssp-postgres-config
  labels:
    app: postgres
  data:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: ${XROAD-SSP-POSTGRES-ADMIN-SECRET}
postgresStorage:
  volName: govstack-xroad-ssp-postgres-pv-volume
  claimName: govstack-xroad-ssp-postgres-pv-claim
  labels:
    type: local
    app: postgres
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/mnt/data"
postgresDeployment:
  name: govstack-xroad-ssp-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: govstack-xroad-ssp-postgres
            image: postgres:12
            imagePullPolicy: "IfNotPresent"
            containerPort: 5432
            configMapRef: govstack-xroad-ssp-postgres-config
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb
            volumeName: postgredb
            volumeClaimName: govstack-xroad-ssp-postgres-pv-claim
postgresService:
  name: govstack-xroad-ssp-postgres
  labels:
    app: postgres
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres
secret:
  postgres:
    adminPassword:
      name: govstack-xroad-ssp-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssp-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssp-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssp-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssp-postgres-messagelog-secret
      type: Opaque  
service:
  name: govstack-xroad-ssp
  type: ClusterIP
deployment:
  name: govstack-xroad-ssp
  containers:
    name: govstack-xroad-ssp
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/${ECR_SS_REPO_NAME}:xroad-ssp
    imagePullPolicy: "Always"
    env:
      - name: "DB_HOST"
        value: "${SSP_DB_HOST}"
      - name: "DB_PORT"
        value: "${SSP_DB_PORT}"
      - name: "DB_ADMIN_USER"
        value: "${SSP_DB_ADMIN_USER}"
      - name: "DB_ADMIN_PASS"
        value: "${SSP_DB_ADMIN_PASS}"                   
      - name: "DB_SERVERCONF_ADMIN_PASS"
        value: "${SSP_DB_SERVERCONF_ADMIN_PASS}"
      - name: "DB_SERVERCONF_PASS"
        value: "${SSP_DB_SERVERCONF_PASS}"
      - name: "DB_NESSAGELOG_ADMIN_PASS"
        value: "${SSP_DB_NESSAGELOG_ADMIN_PASS}"
      - name: "DB_MESSAGELOG_PASS"
        value: "${SSP_DB_MESSAGELOG_PASS}"                                                                

