configMap:
  name: govstack-xroad-ssp-config
  labels:
    app: govstack-xroad-ssp-config
postgresConfigMap:
  name: govstack-xroad-ssp-postgres-config
  labels:
    app: govstack-xroad-ssp-postgres-config
postgresStorage:
  volName: govstack-xroad-ssp-postgres-pv-volume
  claimName: govstack-xroad-ssp-postgres-pv-claim
  labels:
    type: local
    app: postgredb-ssp
  spec:
    storageClassName: manual
    persistentVolumeReclaimPolicy: Delete
    capacity:
      storage: 5Gi
    accessMode: ReadWriteOncePod
    hostPath:
      path: "/data/postgresql"
postgresDeployment:
  name: govstack-xroad-ssp-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres-ssp
    temp:
      metadata:
        labels:
          app: postgres-ssp
      spec:
        containers:
          - name: govstack-xroad-ssp-postgres
            image: postgres:12
            imagePullPolicy: "Always"
            containerPort: 5432
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb-ssp
            volumeName: postgredb-ssp
            volumeClaimName: govstack-xroad-ssp-postgres-pv-claim
            configMapName: govstack-xroad-ssp-postgres-config
        volumes:
          - name: postgredb-ssp
            claimName: govstack-xroad-ssp-postgres-pv-claim
postgresService:
  name: govstack-xroad-ssp-postgres
  labels:
    app: postgres-ssp
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres-ssp
secret:
  postgres:
    adminPassword:
      name: govstack-xroad-ssp-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssp-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssp-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssp-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssp-postgres-messagelog-secret
      type: Opaque  
service:
  name: govstack-xroad-ssp
  type: ClusterIP
deployment:
  name: govstack-xroad-ssp
  containers:
    name: govstack-xroad-ssp
    imageName: xroad-ssp
    imagePullPolicy: "Always"
    configMapName: govstack-xroad-ssp-config
