configMap:
  name: govstack-xroad-ssp-config
  labels:
    app: govstack-xroad-ssp-config
postgresStorage:
  volName: govstack-xroad-ssp-postgres-pv-volume
  claimName: govstack-xroad-ssp-postgres-pv-claim
  labels:
    type: local
    app: postgres-ssp
  spec:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/data/postgresql"
postgresDeployment:
  name: govstack-xroad-ssp-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres-ssp
    template:
      metadata:
        labels:
          app: postgres-ssp
      spec:
        containers:
          - name: govstack-xroad-ssp-postgres
            image: postgres:12
            imagePullPolicy: "IfNotPresent"
            containerPort: 5432
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb-ssp
            volumeName: postgredb-ssp
            volumeClaimName: govstack-xroad-ssp-postgres-pv-claim
            env:
            #  - name: POSTGRES_DB
            #    valueFrom:
            #      secretKeyRef:
            #        name: govstack-xroad-ssp-postgres-admin-db-info-secret
            #        key: dbname
            #  - name: POSTGRES_USER
            #    valueFrom:
            #      secretKeyRef:
            #        name: govstack-xroad-ssp-postgres-admin-db-info-secret
            #        key: username
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssp-postgres-admin-secret
                    key: password             
        volumes:
          - name: postgredb-ssp
            claimName: govstack-xroad-ssp-postgres-pv-claim
postgresService:
  name: govstack-xroad-ssp-postgres
  labels:
    app: postgres-ssp
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres-ssp
secret:
  postgres:
    adminDbInfo:
      name: govstack-xroad-ssp-postgres-admin-db-info-secret
      type: Opaque  
    adminPassword:
      name: govstack-xroad-ssp-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssp-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssp-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssp-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssp-postgres-messagelog-secret
      type: Opaque  
service:
  name: govstack-xroad-ssp
  type: ClusterIP
deployment:
  name: govstack-xroad-ssp
  containers:
    name: govstack-xroad-ssp
    imageName: xroad-ssp
    imagePullPolicy: "Always"
    configMapName: govstack-xroad-ssp-config
