version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.1.2
  helm: circleci/helm@1.0
jobs:
  deploy-project:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - helm/install-helm-client:
          version: v3.0.0
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::463471358064:role/CircleCIRole'
          aws-region: AWS_DEFAULT_REGION
          profile-name: CircleCIRole
          role-session-name: CircleSession
          session-duration: '1800' 
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: GovStack_sandbox
          cluster-authentication-role-arn: arn:aws:iam::463471358064:role/CircleCIRole
      - run:
          name: Debug
          command: aws sts get-caller-identity
      - run:
          name: Update kubectl
          command: |
            aws eks update-kubeconfig --region eu-central-1 --name GovStack_sandbox --role-arn arn:aws:iam::463471358064:role/CircleCIRole 
      - run:
          name: Update Sandbox
          command: |
            helm install information-mediator ./information-mediator/ --dry-run --debug
workflows:
  Deploy project to DEV environment:
    jobs:
      - hold:
          type: approval
      - deploy-project:
          context: aws
          requires: 
            - hold
