version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.1.2
  helm: circleci/helm@1.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  deploy-information-mediator:
    docker:
      - image: cimg/aws:2022.06                
    steps:
      - checkout       
      - setup_remote_docker:
          version: 20.10.14
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::463471358064:role/CICDPipeline_sandbox-bb-information-mediator_Role_dev'
          aws-region: AWS_DEFAULT_REGION
          profile-name: CICDPipeline_sandbox-bb-information-mediator_Role_dev
          role-session-name: CircleSession
          session-duration: '1800' 
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: "${AWS_CLUSTER_NAME}"
          cluster-authentication-role-arn: arn:aws:iam::463471358064:role/CICDPipeline_sandbox-bb-information-mediator_Role_dev
      - run:
          name: Debug
          command: aws sts get-caller-identity
      - run:
          name: Update kubectl
          command: |
            aws eks update-kubeconfig --region "${AWS_DEFAULT_REGION}" --name "${AWS_CLUSTER_NAME}" --role-arn arn:aws:iam::463471358064:role/CICDPipeline_sandbox-bb-information-mediator_Role_dev         
      - run:
          name: Create and deploy container for X-Road Central Server
          command: |
            if [ "$IM_XROAD_CREATE_CS_IMAGE" = true ] ; then
              echo "You Won!"
            else
              echo "You Lose!"
            fi 
      # - run:
      #     name: Create and deploy container for X-Road Security Server with management services 
      #     command: |
      #       echo "Create and deploy container for X-Road Security Server with management services"
      # - run:
      #     name: Create and deploy container for X-Road consumer Security Server 
      #     command: |
      #       echo "Create and deploy container for X-Road consumer Security Server"                         
      # - run:
      #     name: Create and deploy container for X-Road provider Security Server 
      #     command: |
      #       echo "Create and deploy container for X-Road provider Security Server"
      # - run:
      #     name: Install secrets for Information Mediator
      #     command: |
      #       echo "Install secrets for Information Mediator"
      # - run:
      #     name: Install postgres for Information Mediator
      #     command: |
      #       echo "Install postgres for Information Mediator"
      # - run:
      #     name: Configure postgres for Information Mediator
      #     command: |
      #       echo "Configure postgres for Information Mediator"
      # - run:
      #     name: Install X-Road components for Information Mediator
      #     command: |
      #       echo "Install X-Road components for Information Mediator"
      # - run:
      #     name: Delete temporary values file
      #     command: |
      #       echo "Delete temporary values file"               
workflows:
  Deploy IM to EKS cluster:
    jobs:
      - hold:
          type: approval       
      - deploy-information-mediator:
          context: aws
          requires: 
            - hold
