apiVersion: v2
name: information-mediator
description: A Helm chart for Information Mediator
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: xroad-cs
  version: 0.1.0
  repository: file://./charts/xroad-cs
  condition: xroad-cs.enabled
- name: xroad-ssm
  version: 0.1.0
  repository: file://./charts/xroad-ssm
  condition: xroad-ssm.enabled
- name: xroad-ssc
  version: 0.1.0
  repository: file://./charts/xroad-ssc
  condition: xroad-ssc.enabled
- name: xroad-ssp
  version: 0.1.0
  repository: file://./charts/xroad-ssp
  condition: xroad-ssp.enabled    
