apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: ssp-db
  namespace: govstack
spec:
  dbInstanceIdentifier: ssp-db
  engine: postgres
  masterUsername: "postgres"
  masterUserPassword:
    namespace: govstack
    name: "ssp-db-secret"
    key: password
  dbSubnetGroupName: default
  dbInstanceClass: db.t4g.micro
  allocatedStorage: 20
  deletionProtection: false