{{ if .Values.global.db }}
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.db.namespace }}
spec:
  dbInstanceIdentifier: {{ .Values.db.name }}
  engine: {{ .Values.db.engine }}
  masterUsername: {{ .Values.db.masterUsername }}
  masterUserPassword:
    namespace: {{ .Values.db.masterUserPassword.namespace }}
    name: {{ .Values.db.masterUserPassword.name }}
    key: {{ .Values.db.masterUserPassword.key }}
  dbSubnetGroupName: {{ .Values.db.dbSubnetGroupName }}
  dbInstanceClass: {{ .Values.db.dbInstanceClass }}
  allocatedStorage: {{ .Values.db.allocatedStorage }}
  deletionProtection: {{ .Values.db.deletionProtection }}
{{ end }}  
