apiVersion: v1
kind: Service
metadata:
  name: govstack-xroad-ssc
  labels:
    run: govstack-xroad-ssc
  namespace: govstack
spec:
  type: ClusterIP
  selector:
    run: govstack-xroad-ssc
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: config
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http   

