{{ if .Values.global.application }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.deployment.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.application.deployment.name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.application.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.application.deployment.containers.name }}
          image: {{ .Values.global.xroadSecurityServerImageRepo }}:{{ .Values.application.deployment.containers.imageName }}
          imagePullPolicy: {{ .Values.application.deployment.containers.imagePullPolicy }}
          env:
            - name: XROAD_TOKEN_PIN
              value: {{ .Values.global.XROAD_TOKEN_PIN | quote }}
            - name: DB_HOST
              value: {{ .Values.global.SSM_DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.global.SSM_DB_PORT | quote }}
            - name: DB_ADMIN_USER
              value: {{ .Values.global.SSM_DB_ADMIN_USER | quote }}
            - name: DB_ADMIN_PASS
              value: {{ .Values.global.SSM_DB_ADMIN_PASS | quote }}
            - name: DB_SERVERCONF_ADMIN_PASS
              value: {{ .Values.global.SSM_DB_SERVERCONF_ADMIN_PASS | quote }}
            - name: DB_MESSAGELOG_ADMIN_PASS
              value: {{ .Values.global.SSM_DB_MESSAGELOG_ADMIN_PASS | quote }}
            - name: DB_SERVERCONF_PASS
              value: {{ .Values.global.SSM_DB_SERVERCONF_PASS | quote }}
            - name: DB_MESSAGELOG_PASS
              value: {{ .Values.global.SSM_DB_MESSAGELOG_PASS | quote }}
          ports:
            - containerPort: 4000
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.service.name }}
  labels:
    run: {{ .Values.application.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.application.service.type }}
  selector:
    run: {{ .Values.application.service.name }}
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: config
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
{{ end }}