{{ if .Values.global.application }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.deployment.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.application.deployment.name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.application.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.application.deployment.containers.name }}
          image: {{ .Values.global.xroadCentralServerImageRepo }}:{{ .Values.global.xroadCSImageName }}
          imagePullPolicy: {{ .Values.application.deployment.containers.imagePullPolicy }}
          env:
            - name: XROAD_TOKEN_PIN
              value: {{ .Values.global.XROAD_TOKEN_PIN | quote }}
            - name: DB_HOST
              value: {{ .Values.global.CS_DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.global.CS_DB_PORT | quote }}
            - name: DB_ADMIN_USER
              value: {{ .Values.global.CS_DB_ADMIN_USER | quote }}
            - name: DB_ADMIN_PASS
              value: {{ .Values.global.CS_DB_ADMIN_PASS | quote }}
            - name: DB_UI_PASS
              value: {{ .Values.global.CS_DB_UI_PASS | quote }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 4000
            - containerPort: 5500
            - containerPort: 5577
            - containerPort: 5588
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.service.name }}
  labels:
    run: {{ .Values.application.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.application.service.type }}
  selector:
    run: {{ .Values.application.service.name }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: ocsp
    - port: 8899
      targetPort: 8899
      protocol: TCP
      name: tsa
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: name1
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: name2
    - port: 4002
      targetPort: 4002
      protocol: TCP
      name: name3
{{ end }}