{{ if .Values.global.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.deployment.name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.containers.name }}
          image: {{ .Values.global.xroadCentralServerImageRepo }}:{{ .Values.deployment.containers.imageName }}
          imagePullPolicy: {{ .Values.deployment.containers.imagePullPolicy }}
          env:
            - name: XROAD_TOKEN_PIN
              value: {{ .Values.global.XROAD_TOKEN_PIN | quote }}
            - name: DB_HOST
              value: {{ .Values.global.CS_DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.global.CS_DB_PORT | quote }}
            - name: DB_ADMIN_USER
              value: {{ .Values.global.CS_DB_ADMIN_USER | quote }}
            - name: DB_ADMIN_PASS
              value: {{ .Values.global.CS_DB_ADMIN_PASS | quote }}
            - name: DB_UI_PASS
              value: {{ .Values.global.CS_DB_UI_PASS | quote }}
          #envFrom:
          #  - configMapRef:
          #      name: {{ .Values.deployment.containers.configMapName }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 4000
            - containerPort: 5500
            - containerPort: 5577
            - containerPort: 5588
{{ end }}
