{{ if .Values.global.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.deployment.name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.containers.name }}
          image: {{ .Values.global.xroadCentralServerImageRepo }}:{{ .Values.deployment.containers.imageName }}
          imagePullPolicy: {{ .Values.deployment.containers.imagePullPolicy }}
          env:
            {{- range .Values.deployment.containers.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}                    
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 4000
            - containerPort: 5500
            - containerPort: 5577
            - containerPort: 5588
{{ end }}
