{{ if .Values.global.postgres }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresDeployment.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.postgresDeployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgresDeployment.spec.selector.matchLabels.app }}
  serviceName: {{ .Values.service.name }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: {{ .Values.postgresDeployment.spec.temp.metadata.labels.app }}
    spec:
      containers:
        {{- range .Values.postgresDeployment.spec.temp.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports: 
            - containerPort: {{ .containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .configMapName }}
          volumeMounts:
            - mountPath: {{ .volumeMountPath }}
              name: {{ .volumeMountName }}            
        {{- end }}  
      volumes:
        {{- range .Values.postgresDeployment.spec.temp.spec.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}    
{{ end }}            
