{{ if .Values.global.postgres }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresDeployment.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgresDeployment.spec.temp.metadata.labels.app }}
spec:
  replicas: {{ .Values.postgresDeployment.spec.replicas }}
  serviceName: {{ .Values.service.name }}
  selector:
    matchLabels:
      app: {{ .Values.postgresDeployment.spec.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresDeployment.spec.temp.metadata.labels.app }}
    spec:
      containers:
        {{- range .Values.postgresDeployment.spec.temp.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports: 
            - containerPort: {{ .containerPort }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .passwordSecretName }}
                  key: password
          #envFrom:
          #  - configMapRef:
          #      name: {{ .configMapName }}
          volumeMounts:
            - name: {{ .volumeMountName }}
              mountPath: {{ .volumeMountPath }}
        {{- end }}  
  volumeClaimTemplates:
      - metadata:
          name: {{ .Values.postgresStorage.claimName }}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
{{ end }}            
