apiVersion: v1
kind: Secret
metadata:
  name: cs-db-secret
  namespace: govstack
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cs-db-centerui-secret
  namespace: govstack
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}

