{{ if .Values.global.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.postgres.adminDbInfo.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"  
type: {{ .Values.secret.postgres.adminDbInfo.type }}
data:
  dbname: postgres
  username: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.postgres.adminPassword.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: {{ .Values.secret.postgres.adminPassword.type }}
data:
  password: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.postgres.uiPassword.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: {{ .Values.secret.postgres.uiPassword.type }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace ".Values.secret.postgres.uiPassword.name") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $password := (get $secretData ".Values.secret.postgres.uiPassword.name") | default (randAlphaNum 32 | b64enc) }}
  password: {{ $password | quote }}
{{ end }}
