apiVersion: v1
kind: Service
metadata:
  name: govstack-xroad-cs
  labels:
    run: govstack-xroad-cs
  namespace: govstack
spec:
  type: ClusterIP
  selector:
    run: govstack-xroad-cs
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: ocsp
    - port: 8899
      targetPort: 8899
      protocol: TCP
      name: tsa
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: name1
    - port: 4002
      targetPort: 4002
      protocol: TCP
      name: name2
