db:
  name: "ssm-db"
  namespace: "govstack"
  engine: postgres
  masterUsername: "postgres"
  masterUserPassword:
    namespace: govstack
    name: "ssm-db-secret"
    key: password
  dbSubnetGroupName: default
  dbInstanceClass: db.t4g.micro
  allocatedStorage: 20
  deletionProtection: false
secret:
  db:
    adminPassword:
      name: ssm-db-secret
      namespace: govstack
      type: Opaque
    uiPassword:
      name: ssm-db-centerui-secret
      namespace: govstack
      type: Opaque
service:
  name: govstack-xroad-ssm
  namespace: govstack
  type: ClusterIP
deployment:
  name: govstack-xroad-ssm
  namespace: govstack 
  containers:
    name: govstack-xroad-ssm
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/govstackecr:im-xroad-ssm
    imagePullPolicy: "Always"
    env:
      - name: "DB_HOST"
        value: ${SSM_DB_HOST}
      - name: "DB_PORT"
        value: ${SSM_DB_PORT}
      - name: "DB_ADMIN_USER"
        value: ${SSM_DB_ADMIN_USER}
      - name: "DB_ADMIN_PASS"
        value: ${SSM_DB_ADMIN_PASS}                    
      - name: "DB_SERVERCONF_ADMIN_PASS"
        value: ${SSM_DB_SERVERCONF_ADMIN_PASS}
      - name: "DB_SERVERCONF_PASS"
        value: ${SSM_DB_SERVERCONF_PASS}
      - name: "DB_NESSAGELOG_ADMIN_PASS"
        value: ${SSM_DB_NESSAGELOG_ADMIN_PASS}
      - name: "DB_MESSAGELOG_PASS"
        value: ${SSM_DB_MESSAGELOG_PASS}                                                                      

