postgres-configmap:
  name: govstack-xroad-ssm-postgres-config
  namespace: ${NAMESPACE}
  labels:
    app: postgres
  data:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: ${XROAD-SSM-POSTGRES-ADMIN-SECRET}
postgres-storage:
  vol-name: govstack-xroad-ssm-postgres-pv-volume
  claim-name: govstack-xroad-ssm-postgres-pv-claim
  labels:
    type: local
    app: postgres
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/mnt/data"
postgres-deployment:
  name: govstack-xroad-ssm-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: govstack-xroad-ssm-postgres
            image: postgres:12
            imagePullPolicy: "IfNotPresent"
            containerPort: 5432
            configMapRef: govstack-xroad-ssm-postgres-config
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb
            volumeName: postgredb
            volumeClaimName: govstack-xroad-ssm-postgres-pv-claim
postgres-service:
  name: govstack-xroad-ssm-postgres
  labels:
    app: postgres
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres
secret:
  postgres:
    adminPassword:
      name: govstack-xroad-ssm-postgres-admin-secret
      namespace: ${NAMESPACE}
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssm-postgres-serverconf-admin-secret
      namespace: ${NAMESPACE}
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssm-postgres-serverconf-secret
      namespace: ${NAMESPACE}
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssm-postgres-messagelog-admin-secret
      namespace: ${NAMESPACE}
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssm-postgres-messagelog-secret
      namespace: ${NAMESPACE}
      type: Opaque  
service:
  name: govstack-xroad-ssm
  namespace: ${NAMESPACE}
  type: ClusterIP
deployment:
  name: govstack-xroad-ssm
  namespace: ${NAMESPACE} 
  containers:
    name: govstack-xroad-ssm
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/${ECR_SS_REPO_NAME}:xroad-ssm
    imagePullPolicy: "Always"
    env:
      - name: "DB_HOST"
        value: "${SSM_DB_HOST}"
      - name: "DB_PORT"
        value: "${SSM_DB_PORT}"
      - name: "DB_ADMIN_USER"
        value: "${SSM_DB_ADMIN_USER}"
      - name: "DB_ADMIN_PASS"
        value: "${SSM_DB_ADMIN_PASS}"                   
      - name: "DB_SERVERCONF_ADMIN_PASS"
        value: "${SSM_DB_SERVERCONF_ADMIN_PASS}"
      - name: "DB_SERVERCONF_PASS"
        value: "${SSM_DB_SERVERCONF_PASS}"
      - name: "DB_NESSAGELOG_ADMIN_PASS"
        value: "${SSM_DB_NESSAGELOG_ADMIN_PASS}"
      - name: "DB_MESSAGELOG_PASS"
        value: "${SSM_DB_MESSAGELOG_PASS}"                                                               

