postgres:
  storage:
    volName: govstack-xroad-ssm-postgres-pv-volume
    claimName: govstack-xroad-ssm-postgres-pv-claim
    labels:
      type: local
      app: postgres-ssm
    spec:
      storageClassName: manual
      persistentVolumeReclaimPolicy: Delete
      capacity:
        storage: 5Gi
      accessMode: ReadWriteOnce
      hostPath:
        path: "/mnt/data"
  deployment:
    name: govstack-xroad-ssm-postgres
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgres-ssm
      temp:
        metadata:
          labels:
            app: postgres-ssm
        spec:
          containers:
              name: govstack-xroad-ssm-postgres
              image: postgres:12
              imagePullPolicy: "Always"
              containerPort: 5432
              volumeMountName: postgredb-ssm
              volumeName: postgredb-ssm
              passwordSecretName: govstack-xroad-ssm-postgres-admin-secret
              volumeClaimName: govstack-xroad-ssm-postgres-pv-claim
          volumes:
            - name: postgredb-ssm
              claimName: govstack-xroad-ssm-postgres-pv-claim
  service:
    name: govstack-xroad-ssm-postgres
    labels:
      app: postgres-ssm
    spec:
      type: NodePort
      port: 5432
      selector:
        app: postgres-ssm
secret:
  postgres:
    adminPassword:
      name: govstack-xroad-ssm-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssm-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssm-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssm-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssm-postgres-messagelog-secret
      type: Opaque  
application:
  service:
    name: govstack-xroad-ssm
    type: ClusterIP
  deployment:
    name: govstack-xroad-ssm
    containers:
      name: govstack-xroad-ssm
      imagePullPolicy: "Always"
