postgresConfigMap:
  name: govstack-xroad-ssm-postgres-config
  labels:
    app: postgres
  data:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: ${XROAD_SSM_POSTGRES_ADMIN_SECRET}
postgresStorage:
  volName: govstack-xroad-ssm-postgres-pv-volume
  claimName: govstack-xroad-ssm-postgres-pv-claim
  labels:
    type: local
    app: postgres
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/mnt/data"
postgresDeployment:
  name: govstack-xroad-ssm-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: govstack-xroad-ssm-postgres
            image: postgres:12
            imagePullPolicy: "IfNotPresent"
            containerPort: 5432
            configMapRef: govstack-xroad-ssm-postgres-config
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb
            volumeName: postgredb
            volumeClaimName: govstack-xroad-ssm-postgres-pv-claim
        volumes:
          - name: postgredb
            claimName: govstack-xroad-ssm-postgres-pv-claim
postgresService:
  name: govstack-xroad-ssm-postgres
  labels:
    app: postgres
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres
secret:
  postgres:
    adminPassword:
      name: govstack-xroad-ssm-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssm-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssm-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssm-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssm-postgres-messagelog-secret
      type: Opaque  
service:
  name: govstack-xroad-ssm
  type: ClusterIP
deployment:
  name: govstack-xroad-ssm
  containers:
    name: govstack-xroad-ssm
    imageName: xroad-ssm
    imagePullPolicy: "Always"
    env:
      - name: "DB_HOST"
        value: "${SSM_DB_HOST}"
      - name: "DB_PORT"
        value: "${SSM_DB_PORT}"
      - name: "DB_ADMIN_USER"
        value: "${SSM_DB_ADMIN_USER}"
      - name: "DB_ADMIN_PASS"
        value: "${SSM_DB_ADMIN_PASS}"                   
      - name: "DB_SERVERCONF_ADMIN_PASS"
        value: "${SSM_DB_SERVERCONF_ADMIN_PASS}"
      - name: "DB_SERVERCONF_PASS"
        value: "${SSM_DB_SERVERCONF_PASS}"
      - name: "DB_NESSAGELOG_ADMIN_PASS"
        value: "${SSM_DB_NESSAGELOG_ADMIN_PASS}"
      - name: "DB_MESSAGELOG_PASS"
        value: "${SSM_DB_MESSAGELOG_PASS}"                                                               

