configMap:
  name: govstack-xroad-ssm-config
  labels:
    app: govstack-xroad-ssm-config
postgresStorage:
  volName: govstack-xroad-ssm-postgres-pv-volume
  claimName: govstack-xroad-ssm-postgres-pv-claim
  labels:
    type: local
    app: postgres-ssm
  spec:
    storageClassName: manual
    capacity:
      storage: 2Gi
    accessMode: ReadWriteOnce
    hostPath:
      path: "/mnt/data"
postgresDeployment:
  name: govstack-xroad-ssm-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres-ssm
    template:
      metadata:
        labels:
          app: postgres-ssm
      spec:
        containers:
          - name: govstack-xroad-ssm-postgres
            image: postgres:12
            imagePullPolicy: "Always"
            containerPort: 5432
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb-ssm
            volumeName: postgredb-ssm
            volumeClaimName: govstack-xroad-ssm-postgres-pv-claim
            env:
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssm-postgres-admin-db-info-secret
                    key: dbname 
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssm-postgres-admin-db-info-secret
                    key: username             
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: govstack-xroad-ssm-postgres-admin-secret
                    key: password             
        volumes:
          - name: postgredb-ssm
            claimName: govstack-xroad-ssm-postgres-pv-claim
postgresService:
  name: govstack-xroad-ssm-postgres
  labels:
    app: postgres-ssm
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres-ssm
secret:
  postgres:
    adminDbInfo:
      name: govstack-xroad-ssm-postgres-admin-db-info-secret
      type: Opaque  
    adminPassword:
      name: govstack-xroad-ssm-postgres-admin-secret
      type: Opaque
    serverConfAdminPassword:
      name: govstack-xroad-ssm-postgres-serverconf-admin-secret
      type: Opaque
    serverConfPassword:
      name: govstack-xroad-ssm-postgres-serverconf-secret
      type: Opaque
    messageLogAdminPassword:
      name: govstack-xroad-ssm-postgres-messagelog-admin-secret
      type: Opaque
    messageLogPassword:
      name: govstack-xroad-ssm-postgres-messagelog-secret
      type: Opaque  
service:
  name: govstack-xroad-ssm
  type: ClusterIP
deployment:
  name: govstack-xroad-ssm
  containers:
    name: govstack-xroad-ssm
    imageName: xroad-ssm
    imagePullPolicy: "Always"
    configMapName: govstack-xroad-ssm-config
